### ISSUE TITLE
New release to kill deprecation warning.

### ISSUE THREAD

**Issue by sbryant** [bleikamp/language-processing#10]
Yo @bleikamp getting a deprecation warning and it's *killing* me. :skull: 

I see someone already actually got the fix in, can we just get a new release. :heart:

**Comment by bleikamp** [comment]
Whoops—yeah, I can do the `apm publish` thing

**Comment by bleikamp** [comment]
Closed via https://github.com/bleikamp/language-processing/commit/1fa11647231151a86749fb0e195e30b647f9f78a
